# Data agumentation train img

In [12]:
import random
import numpy as np
import os
from PIL import Image

file_path = 'data4/train/img'
file_names = os.listdir(file_path)

for file_name in file_names:
     image = Image.open(os.path.join(file_path,file_name))
     inverted_image = image.transpose(Image.FLIP_LEFT_RIGHT)
     inverted_image.save(file_path + '/inverted_' + file_name)
     rotated_image = image.rotate(random.randrange(-20, 20))
     rotated_image.save(file_path + '/rotated_' + file_name)
     inverted_image2 = image.transpose(Image.FLIP_TOP_BOTTOM)
     inverted_image2.save(file_path + '/inverted2_' + file_name)

# Data agumentation train mask

In [13]:
import random
import numpy as np
import os
from PIL import Image

file_path = 'data4/train/masks'
file_names = os.listdir(file_path)

for file_name in file_names:
     image = Image.open(os.path.join(file_path,file_name))
     inverted_image = image.transpose(Image.FLIP_LEFT_RIGHT)
     inverted_image.save(file_path + '/inverted_' + file_name)
     rotated_image = image.rotate(random.randrange(-20, 20))
     rotated_image.save(file_path + '/rotated_' + file_name)
     inverted_image2 = image.transpose(Image.FLIP_TOP_BOTTOM)
     inverted_image2.save(file_path + '/inverted2_' + file_name)

In [9]:
import numpy as np
from PIL import Image

img = Image.open('data4/train/masks/inverted_1.png')

img = np.array(img)

# 3차원 배열을 2차원으로 변환
arr_2d = img.reshape(-1, img.shape[-1])

# 2차원 배열에서 unique한 값을 구함
unique_2d = np.unique(arr_2d, axis=0)

# 결과 출력
print(unique_2d)
print(len(unique_2d))

[[  0   0   0]
 [  0   0 128]
 [  0   0 255]
 [  0  67   0]
 [  0 128 128]
 [  0 255   0]
 [  0 255 255]
 [128   0   0]
 [128   0 128]
 [128 128   0]
 [128 128 128]
 [192 192 192]
 [255   0   0]
 [255   0 255]
 [255 255   0]]
15
